export const entityDefinitions = [
  {
    key: "customers",
    label: "Customers",
    description: "Manage customer contact and address details.",
    idFields: ["customer_id"],
    columns: ["customer_id", "name", "phone", "email", "street", "city", "state", "pincode"],
    formFields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "phone", label: "Phone", type: "text", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "street", label: "Street", type: "text", required: true },
      { name: "city", label: "City", type: "text", required: true },
      { name: "state", label: "State", type: "text", required: true },
      { name: "pincode", label: "Pincode", type: "text", required: true },
    ],
  },
  {
    key: "employees",
    label: "Employees",
    description: "Track chefs and managers.",
    idFields: ["employee_id"],
    columns: ["employee_id", "name", "role", "phone", "email", "salary", "join_date"],
    formFields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "role", label: "Role", type: "select", required: true, options: ["Chef", "Manager"] },
      { name: "phone", label: "Phone", type: "text", required: true },
      { name: "email", label: "Email", type: "email" },
      { name: "salary", label: "Salary", type: "number", required: true, step: "0.01" },
      { name: "join_date", label: "Join Date", type: "date", required: true },
    ],
  },
  {
    key: "menu-items",
    label: "Menu Items",
    description: "Maintain dishes, prices, and availability.",
    idFields: ["menu_item_id"],
    columns: ["menu_item_id", "item_name", "price", "category", "availability_status"],
    formFields: [
      { name: "item_name", label: "Item Name", type: "text", required: true },
      { name: "price", label: "Price", type: "number", required: true, step: "0.01" },
      { name: "category", label: "Category", type: "text", required: true },
      {
        name: "availability_status",
        label: "Availability Status",
        type: "select",
        required: true,
        options: ["Available", "Not Available"],
      },
    ],
  },
  {
    key: "inventory-items",
    label: "Inventory Items",
    description: "Watch stock levels and expiry dates.",
    idFields: ["inventory_item_id"],
    columns: ["inventory_item_id", "item_name", "unit", "stock_quantity", "reorder_level", "expiry_date"],
    formFields: [
      { name: "item_name", label: "Item Name", type: "text", required: true },
      { name: "unit", label: "Unit", type: "text", required: true },
      { name: "stock_quantity", label: "Stock Quantity", type: "number", required: true, step: "0.01" },
      { name: "reorder_level", label: "Reorder Level", type: "number", required: true, step: "0.01" },
      { name: "expiry_date", label: "Expiry Date", type: "date" },
    ],
  },
  {
    key: "suppliers",
    label: "Suppliers",
    description: "Store supplier contacts and ratings.",
    idFields: ["supplier_id"],
    columns: ["supplier_id", "supplier_name", "company_name", "phone", "rating"],
    formFields: [
      { name: "supplier_name", label: "Supplier Name", type: "text", required: true },
      { name: "company_name", label: "Company Name", type: "text" },
      { name: "phone", label: "Phone", type: "text", required: true },
      { name: "rating", label: "Rating", type: "number", step: "0.1" },
    ],
  },
  {
    key: "orders",
    label: "Orders",
    description: "Manage customer orders and status.",
    idFields: ["order_id"],
    columns: ["order_id", "order_date", "order_status", "total_amount", "customer_id", "employee_id"],
    formFields: [
      { name: "order_date", label: "Order Date", type: "datetime-local", required: true },
      {
        name: "order_status",
        label: "Order Status",
        type: "select",
        required: true,
        options: ["Placed", "Preparing", "Ready", "Completed", "Cancelled"],
      },
      { name: "total_amount", label: "Total Amount", type: "number", step: "0.01" },
      { name: "customer_id", label: "Customer ID", type: "number", required: true },
      { name: "employee_id", label: "Employee ID", type: "number" },
    ],
  },
  {
    key: "order-items",
    label: "Order Items",
    description: "Connect orders with menu items.",
    idFields: ["order_item_id"],
    columns: ["order_item_id", "quantity", "item_price", "subtotal", "order_id", "menu_item_id"],
    formFields: [
      { name: "quantity", label: "Quantity", type: "number", required: true },
      { name: "item_price", label: "Item Price", type: "number", required: true, step: "0.01" },
      { name: "subtotal", label: "Subtotal", type: "number", step: "0.01" },
      { name: "order_id", label: "Order ID", type: "number", required: true },
      { name: "menu_item_id", label: "Menu Item ID", type: "number", required: true },
    ],
  },
  {
    key: "bills",
    label: "Bills",
    description: "Capture payment details for each order.",
    idFields: ["bill_id"],
    columns: ["bill_id", "final_amount", "tax_amount", "payment_mode", "payment_status", "order_id"],
    formFields: [
      { name: "final_amount", label: "Final Amount", type: "number", required: true, step: "0.01" },
      { name: "tax_amount", label: "Tax Amount", type: "number", required: true, step: "0.01" },
      { name: "payment_mode", label: "Payment Mode", type: "select", required: true, options: ["Cash", "Card", "UPI"] },
      { name: "payment_status", label: "Payment Status", type: "select", required: true, options: ["Pending", "Paid", "Failed"] },
      { name: "order_id", label: "Order ID", type: "number", required: true },
    ],
  },
  {
    key: "recipes",
    label: "Recipes",
    description: "Store cooking instructions for menu items.",
    idFields: ["recipe_id"],
    columns: ["recipe_id", "instructions", "menu_item_id"],
    formFields: [
      { name: "instructions", label: "Instructions", type: "textarea", required: true },
      { name: "menu_item_id", label: "Menu Item ID", type: "number", required: true },
    ],
  },
  {
    key: "recipe-ingredients",
    label: "Recipe Ingredients",
    description: "Manage recipe to inventory relationships.",
    idFields: ["recipe_id", "inventory_item_id"],
    columns: ["recipe_id", "inventory_item_id", "quantity_required", "measurement_unit"],
    formFields: [
      { name: "recipe_id", label: "Recipe ID", type: "number", required: true },
      { name: "inventory_item_id", label: "Inventory Item ID", type: "number", required: true },
      { name: "quantity_required", label: "Quantity Required", type: "number", required: true, step: "0.01" },
      { name: "measurement_unit", label: "Measurement Unit", type: "text", required: true },
    ],
  },
  {
    key: "purchase-orders",
    label: "Purchase Orders",
    description: "Track procurement from suppliers.",
    idFields: ["purchase_order_id"],
    columns: ["purchase_order_id", "purchase_date", "status", "supplier_id", "employee_id"],
    formFields: [
      { name: "purchase_date", label: "Purchase Date", type: "datetime-local", required: true },
      {
        name: "status",
        label: "Status",
        type: "select",
        required: true,
        options: ["Requested", "Ordered", "Received", "Cancelled"],
      },
      { name: "supplier_id", label: "Supplier ID", type: "number", required: true },
      { name: "employee_id", label: "Employee ID", type: "number", required: true },
    ],
  },
  {
    key: "purchase-order-items",
    label: "Purchase Order Items",
    description: "Store purchase order item details.",
    idFields: ["purchase_order_item_id"],
    columns: ["purchase_order_item_id", "quantity", "unit_price", "purchase_order_id", "inventory_item_id"],
    formFields: [
      { name: "quantity", label: "Quantity", type: "number", required: true, step: "0.01" },
      { name: "unit_price", label: "Unit Price", type: "number", required: true, step: "0.01" },
      { name: "purchase_order_id", label: "Purchase Order ID", type: "number", required: true },
      { name: "inventory_item_id", label: "Inventory Item ID", type: "number", required: true },
    ],
  },
];

export const viewDefinitions = [
  {
    key: "customer-order-summary",
    label: "Customer Order Summary",
    columns: ["name", "order_id", "final_amount"],
  },
  {
    key: "low-stock-inventory",
    label: "Low Stock Inventory",
    columns: ["item_name", "stock_quantity", "reorder_level"],
  },
];
